module.exports = {
  title: "leekh8's Blog",
  description: "Hello :)",
  author: "leekh8",
  siteUrl: "https://leekh8.github.io/",
  links: {
    timetrack:"https://time-track-psi.vercel.app/",
    sitemapper: "https://site-mapper.onrender.com/",
    mdggu: "https://mdggu-front.onrender.com/",
    github: "https://github.com/leekh8",
    // linkedIn: "https://linkedin.com",
    // facebook: "https://www.facebook.com",
    // twitter: "https://twitter.com",
    // x: "https://x.com",
    // instagram: "https://www.instagram.com",
    // medium: "https://medium.com",
    // blogger: "https://blogger.com",
    email: "mailto:amysun125@gmail.com",
    // resume: "https://leekh8.blog",
    // link: "https://leekh8.blog",
  },
  utterances: {
    repo: "leekh8/gatsby-starter-hoodie",
    type: "pathname",
  },
}
