module.exports = {
  title: "leekh8's Blog",
  description: "보안, 웹 개발, Python을 다루는 기술 블로그",
  author: "leekh8",
  siteUrl: "https://leekh8.github.io",
  googleAnalyticsId: "G-TE1CVMQ9CN",
  links: {
    about: "/about",
    contact: "/contact",
    privacypolicy: "/privacy-policy",
    terms: "/terms",
    timetrack: "https://time-track-psi.vercel.app/",
    sitemapper: "https://site-mapper.onrender.com/",
    mdggu: "https://mdggu-front.onrender.com/",
    github: "https://github.com/leekh8",
    // linkedIn: "https://linkedin.com",
    // facebook: "https://www.facebook.com",
    // twitter: "https://twitter.com",
    // x: "https://x.com",
    // instagram: "https://www.instagram.com",
    // medium: "https://medium.com",
    // blogger: "https://blogger.com",
    email: "mailto:leekh8.contact@gmail.com",
    // resume: "https://leekh8.blog",
    // link: "https://leekh8.blog",
  },
  utterances: {
    repo: "leekh8/leekh8.github.io",
    type: "pathname",
  },
}
